<?php
/**
 * Created by PhpStorm.
 * User: mingzhanghui
 * Date: 12/18/2019
 * Time: 10:31
 */

namespace app\command;

use think\console\Command;
use think\console\Input;
use think\console\input\Argument;
use think\console\input\Option;
use think\console\Output;

/**
 * Usage:
 * $ php artisan hello mingzhanghui --city Wuhan
 * Hello, mingzhanghui!
 * From Wuhan
 * Class Hello
 * @package app\command
 */
class Hello extends Command
{
    protected function configure() {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('hello')->addArgument('name', Argument::OPTIONAL, "your name")
            ->addOption("city", null, Option::VALUE_REQUIRED, "city name")
            ->setDescription("Say hello");
    }

    /**
     * @param Input $input
     * @param Output $output
     * @return int|null|void
     */
    protected function execute(Input $input, Output $output) {
        $name = trim($input->getArgument("name"));
        $name = $name ?: 'thinkphp';

        $city = "";
        if ($input->hasOption("city")) {
            $city = PHP_EOL."From ".$input->getOption("city");
        }
        $output->writeln("Hello, ".$name.'! '.$city);
    }
}